<?php

namespace ContainerKit99vq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WFeFjGJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WFeFjGJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WFeFjGJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entity' => ['privates', '.errored..service_locator.WFeFjGJ.App\\Entity\\Propiedades', NULL, 'Cannot autowire service ".service_locator.WFeFjGJ": it references class "App\\Entity\\Propiedades" but no such service exists.'],
            'handler' => ['privates', 'App\\Form\\Handler\\SaveCommonFormHandler', 'getSaveCommonFormHandlerService', true],
        ], [
            'entity' => 'App\\Entity\\Propiedades',
            'handler' => 'App\\Form\\Handler\\SaveCommonFormHandler',
        ]);
    }
}
