<?php

namespace ContainerKit99vq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L0M6QzlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.L0M6Qzl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L0M6Qzl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'handler' => ['privates', 'App\\Form\\Handler\\SaveCommonFormHandler', 'getSaveCommonFormHandlerService', true],
        ], [
            'handler' => 'App\\Form\\Handler\\SaveCommonFormHandler',
        ]);
    }
}
