<?php

namespace ContainerKit99vq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A_SWPjwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A.SWPjw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A.SWPjw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entity' => ['privates', '.errored..service_locator.A.SWPjw.App\\Entity\\Areas', NULL, 'Cannot autowire service ".service_locator.A.SWPjw": it references class "App\\Entity\\Areas" but no such service exists.'],
            'helper' => ['privates', 'App\\Zennovia\\Common\\EntityManagerHelper', 'getEntityManagerHelperService', true],
        ], [
            'entity' => 'App\\Entity\\Areas',
            'helper' => 'App\\Zennovia\\Common\\EntityManagerHelper',
        ]);
    }
}
