<?php

namespace ContainerKit99vq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S7AY5qUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s7AY5qU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s7AY5qU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entity' => ['privates', '.errored..service_locator.s7AY5qU.App\\Entity\\Group', NULL, 'Cannot autowire service ".service_locator.s7AY5qU": it references class "App\\Entity\\Group" but no such service exists.'],
            'handler' => ['privates', 'App\\Form\\Handler\\SaveCommonFormHandler', 'getSaveCommonFormHandlerService', true],
        ], [
            'entity' => 'App\\Entity\\Group',
            'handler' => 'App\\Form\\Handler\\SaveCommonFormHandler',
        ]);
    }
}
