<?php

namespace ContainerKit99vq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAreas2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CTFArkb.App\Entity\Areas' shared service.
     *
     * @return \App\Entity\Areas
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.CTFArkb": it references class "App\\Entity\\Areas" but no such service exists.');
    }
}
