<?php

namespace ContainerKit99vq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChangePasswordFormHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Handler\ChangePasswordFormHandler' shared autowired service.
     *
     * @return \App\Form\Handler\ChangePasswordFormHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Zennovia/Common/BaseFormHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Handler/ChangePasswordFormHandler.php';

        return $container->privates['App\\Form\\Handler\\ChangePasswordFormHandler'] = new \App\Form\Handler\ChangePasswordFormHandler(($container->services['.container.private.form.factory'] ?? $container->load('get_Container_Private_Form_FactoryService')), ($container->privates['App\\Zennovia\\Common\\EntityManagerHelper'] ?? $container->load('getEntityManagerHelperService')), ($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService')));
    }
}
