<?php

namespace ContainerKit99vq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomGroupedChoicesTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\Custom\CustomGroupedChoicesType' shared autowired service.
     *
     * @return \App\Form\Type\Custom\CustomGroupedChoicesType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/Custom/CustomGroupedChoicesType.php';

        return $container->privates['App\\Form\\Type\\Custom\\CustomGroupedChoicesType'] = new \App\Form\Type\Custom\CustomGroupedChoicesType();
    }
}
