<?php

namespace ContainerKit99vq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmpleadoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\EmpleadoController' shared autowired service.
     *
     * @return \App\Controller\EmpleadoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Zennovia/Common/BaseController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/EmpleadoController.php';

        $container->services['App\\Controller\\EmpleadoController'] = $instance = new \App\Controller\EmpleadoController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\EmpleadoController', $container));

        return $instance;
    }
}
