<?php

namespace ContainerKit99vq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecoverPasswordFormHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Handler\RecoverPasswordFormHandler' shared autowired service.
     *
     * @return \App\Form\Handler\RecoverPasswordFormHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Zennovia/Common/BaseFormHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Handler/RecoverPasswordFormHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Zennovia/Common/BaseSendMailHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Service/RecoverPassword.php';

        $a = new \App\Service\RecoverPassword(($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), ($container->services['swiftmailer.mailer.default'] ?? $container->load('getSwiftmailer_Mailer_DefaultService')));
        $a->setFrom('no_reply@zennovia.com');

        return $container->privates['App\\Form\\Handler\\RecoverPasswordFormHandler'] = new \App\Form\Handler\RecoverPasswordFormHandler(($container->services['.container.private.form.factory'] ?? $container->load('get_Container_Private_Form_FactoryService')), ($container->privates['App\\Zennovia\\Common\\EntityManagerHelper'] ?? $container->load('getEntityManagerHelperService')), ($container->services['translator'] ?? $container->getTranslatorService()), $a);
    }
}
