<?php

namespace ContainerKit99vq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSwitchUserSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SwitchUserSubscriber' shared autowired service.
     *
     * @return \App\Service\SwitchUserSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/SwitchUserSubscriber.php';

        return $container->privates['App\\Service\\SwitchUserSubscriber'] = new \App\Service\SwitchUserSubscriber(($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()));
    }
}
