<?php

namespace ContainerPt5fYhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CkN1MWvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ckN1MWv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ckN1MWv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entity' => ['privates', '.errored..service_locator.ckN1MWv.App\\Entity\\Empleados', NULL, 'Cannot autowire service ".service_locator.ckN1MWv": it references class "App\\Entity\\Empleados" but no such service exists.'],
            'helper' => ['privates', 'App\\Zennovia\\Common\\EntityManagerHelper', 'getEntityManagerHelperService', true],
        ], [
            'entity' => 'App\\Entity\\Empleados',
            'helper' => 'App\\Zennovia\\Common\\EntityManagerHelper',
        ]);
    }
}
