<?php

namespace ContainerPt5fYhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SYODbPDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sYODbPD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sYODbPD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'handler' => ['privates', 'App\\Form\\Handler\\SaveUserFormHandler', 'getSaveUserFormHandlerService', true],
        ], [
            'handler' => 'App\\Form\\Handler\\SaveUserFormHandler',
        ]);
    }
}
