<?php

namespace ContainerPt5fYhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XGNTUHKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xGNTUHK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xGNTUHK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'area' => ['privates', '.errored..service_locator.xGNTUHK.App\\Entity\\Areas', NULL, 'Cannot autowire service ".service_locator.xGNTUHK": it references class "App\\Entity\\Areas" but no such service exists.'],
            'helper' => ['privates', 'App\\Zennovia\\Common\\FindEntitiesHelper', 'getFindEntitiesHelperService', true],
        ], [
            'area' => 'App\\Entity\\Areas',
            'helper' => 'App\\Zennovia\\Common\\FindEntitiesHelper',
        ]);
    }
}
