<?php

namespace ContainerPt5fYhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mm1SujMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Mm1SujM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Mm1SujM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entity' => ['privates', '.errored..service_locator.Mm1SujM.App\\Entity\\Empleados', NULL, 'Cannot autowire service ".service_locator.Mm1SujM": it references class "App\\Entity\\Empleados" but no such service exists.'],
            'handler' => ['privates', 'App\\Form\\Handler\\SaveCommonFormHandler', 'getSaveCommonFormHandlerService', true],
        ], [
            'entity' => 'App\\Entity\\Empleados',
            'handler' => 'App\\Form\\Handler\\SaveCommonFormHandler',
        ]);
    }
}
