<?php

namespace ContainerPt5fYhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wev3T60Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wev3T60' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wev3T60'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entity' => ['privates', '.errored..service_locator.wev3T60.App\\Entity\\Group', NULL, 'Cannot autowire service ".service_locator.wev3T60": it references class "App\\Entity\\Group" but no such service exists.'],
        ], [
            'entity' => 'App\\Entity\\Group',
        ]);
    }
}
