<?php

namespace ContainerPt5fYhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7NWWFfeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7NWWFfe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7NWWFfe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'propiedad' => ['privates', '.errored..service_locator.7NWWFfe.App\\Entity\\Propiedades', NULL, 'Cannot autowire service ".service_locator.7NWWFfe": it references class "App\\Entity\\Propiedades" but no such service exists.'],
        ], [
            'propiedad' => 'App\\Entity\\Propiedades',
        ]);
    }
}
