<?php

namespace ContainerPt5fYhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UZlKGJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UZlKG_j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UZlKG_j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'helper' => ['privates', 'App\\Zennovia\\Common\\FindEntitiesHelper', 'getFindEntitiesHelperService', true],
        ], [
            'helper' => 'App\\Zennovia\\Common\\FindEntitiesHelper',
        ]);
    }
}
