<?php

namespace ContainerPt5fYhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBaseControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Zennovia\Common\BaseController' shared autowired service.
     *
     * @return \App\Zennovia\Common\BaseController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Zennovia/Common/BaseController.php';

        $container->services['App\\Zennovia\\Common\\BaseController'] = $instance = new \App\Zennovia\Common\BaseController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Zennovia\\Common\\BaseController', $container));

        return $instance;
    }
}
