<?php

namespace ContainerPt5fYhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomFromAndToDateTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\Custom\CustomFromAndToDateType' shared autowired service.
     *
     * @return \App\Form\Type\Custom\CustomFromAndToDateType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/Custom/CustomFromAndToDateType.php';

        return $container->privates['App\\Form\\Type\\Custom\\CustomFromAndToDateType'] = new \App\Form\Type\Custom\CustomFromAndToDateType(($container->services['translator'] ?? $container->getTranslatorService()));
    }
}
