<?php

namespace ContainerPt5fYhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFindEntitiesHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Zennovia\Common\FindEntitiesHelper' shared autowired service.
     *
     * @return \App\Zennovia\Common\FindEntitiesHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Zennovia/Common/FindEntitiesHelper.php';
        include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-components/src/Knp/Component/Pager/PaginatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-components/src/Knp/Component/Pager/Paginator.php';

        $a = ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));

        return $container->privates['App\\Zennovia\\Common\\FindEntitiesHelper'] = new \App\Zennovia\Common\FindEntitiesHelper($a, new \Knp\Component\Pager\Paginator(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), $a));
    }
}
