<?php

namespace ContainerPt5fYhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPropiedades2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WFeFjGJ.App\Entity\Propiedades' shared service.
     *
     * @return \App\Entity\Propiedades
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.WFeFjGJ": it references class "App\\Entity\\Propiedades" but no such service exists.');
    }
}
