<?php

namespace ContainerSOZcJpx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UOgsL7tService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uOgsL7t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uOgsL7t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'handler' => ['privates', 'App\\Form\\Handler\\ChangePasswordFormHandler', 'getChangePasswordFormHandlerService', true],
        ], [
            'handler' => 'App\\Form\\Handler\\ChangePasswordFormHandler',
        ]);
    }
}
