<?php

namespace ContainerSOZcJpx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RMwzt75Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rMwzt75' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rMwzt75'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'handler' => ['privates', 'App\\Form\\Handler\\RecoverPasswordFormHandler', 'getRecoverPasswordFormHandlerService', true],
        ], [
            'handler' => 'App\\Form\\Handler\\RecoverPasswordFormHandler',
        ]);
    }
}
