<?php

namespace ContainerSOZcJpx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmpleados3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ckN1MWv.App\Entity\Empleados' shared service.
     *
     * @return \App\Entity\Empleados
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ckN1MWv": it references class "App\\Entity\\Empleados" but no such service exists.');
    }
}
