<?php

namespace ContainerSOZcJpx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntityManagerHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Zennovia\Common\EntityManagerHelper' shared autowired service.
     *
     * @return \App\Zennovia\Common\EntityManagerHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Zennovia/Common/EntityManagerHelper.php';

        return $container->privates['App\\Zennovia\\Common\\EntityManagerHelper'] = new \App\Zennovia\Common\EntityManagerHelper(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['.container.private.validator'] ?? $container->get_Container_Private_ValidatorService()));
    }
}
