<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWgezPnx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWgezPnx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWgezPnx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWgezPnx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWgezPnx\App_KernelDevDebugContainer([
    'container.build_hash' => 'WgezPnx',
    'container.build_id' => 'eb64fda2',
    'container.build_time' => 1644239684,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWgezPnx');
