<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKit99vq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKit99vq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKit99vq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKit99vq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKit99vq\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kit99vq',
    'container.build_id' => 'b92f3e42',
    'container.build_time' => 1640608103,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKit99vq');
