<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIVYaKKU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIVYaKKU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIVYaKKU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIVYaKKU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIVYaKKU\App_KernelDevDebugContainer([
    'container.build_hash' => 'IVYaKKU',
    'container.build_id' => 'cc1283b8',
    'container.build_time' => 1646395144,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIVYaKKU');
